include:
  - webserver.yaml

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    healthcheck:
      test: curl -fsS localhost:8080
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
