include:
  - webserver.yaml

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD", "pg_isready"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
