FROM maven:3.9.9-eclipse-temurin-21-alpine AS builder

WORKDIR /usr/local/src
COPY . .

RUN mvn clean package


# Build Image
FROM maven:3.9.9-eclipse-temurin-21-alpine
RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY --from=builder /usr/local/src/target/web-server-0.0.1.jar .

CMD ["java", "-jar", "web-server-0.0.1.jar"]
