name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy Java to docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Extract App Version
        run: |
          POM_VERSION="POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          echo "Pom version is $POM_VERSION"
          echo $POM_VERSION >> $GITHUB_ENV

      - name: build
        run: mvn --batch-mode clean package

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/main/docker/Dockerfile
          context: .
          platforms: >-
            linux/amd64,
            linux/arm64
          push: true
          tags: >-
            ghcr.io/jakobhuemer/3ahitm-itp-webserver:latest,
            ghcr.io/jakobhuemer/3ahitm-itp-webserver:${{ env.POM_VERSION }}